services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ProjectCompDist
      MONGO_INITDB_ROOT_USERNAME: alisondomingos
      MONGO_INITDB_ROOT_PASSWORD: gEo43utzu1T5Ufyq
    volumes:
      - dbdata:/data/db # Persistir dados usando volumes
  api:
    image: node:latest
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  dbdata:
